### ISSUE TITLE
Environment Creation

### ISSUE THREAD

**Issue by gautam1858** [TuragaLab/flybody#2]
Hi,

If i have to create an environment and then export the same to MuJoCo in XML format, what kind of CAD tool should I use to design the environment ?

-GR

**Comment by vaxenburg** [comment]
Looks like you could try using SolidWorks, as described in this MuJoCo issue: https://github.com/google-deepmind/mujoco/issues/1352 .
Probably Blender could also be used to some extent, along with the `dm_control` Blender-to-MuJoCo [exporter](https://github.com/google-deepmind/dm_control/tree/main/dm_control/blender/mujoco_exporter).

**Comment by gautam1858** [comment]
Thank you. Are there any tutorials for these or a write up to just understand how to design on Blender, then export it to MuJoCo and later do some simulation ?

**Comment by vaxenburg** [comment]
I'm not aware of such tutorials except maybe this https://github.com/Balint-H/blender-mjcf. But I'm not sure if you actually need any of these CAD-like tools because you can just create scenes programmatically.
