### ISSUE TITLE
Controlling the fly legs using torque control

### ISSUE THREAD

**Issue by Er1ckR0mo** [TuragaLab/flybody#5]
Hi! From your paper, I see the wings can be controlled by inputting torques. My question is, can I do the same with the leg joints?
Also, what units should the input torque be?
Thanks!

**Comment by Er1ckR0mo** [comment]
Thank you for your reply! May I ask two more doubts:
How do you select the components of the actuator, such as forcerange, etc.? 

Also, how are the damping and stiffness values of the joint selected? Are these based on literature or trial and error?

Thanks!

**Comment by vaxenburg** [comment]
Most of these things are pretty loose for now. The actuator parameters are mostly educated guesses. For example you can use some fly walking videos to estimate the leg velocity and/or acceleration and then roughly estimate the force ballpark. Trial and error also works:)

One choice of damping could be to use critical damping (for given actuator gain), you can try calculating it with a function [like this](https://github.com/vaxenburg/mujoco_utils/blob/main/mujoco_utils/physics_utils.py#L65).

Getting better estimates for some of these parameters could be an interesting project.

**Comment by Er1ckR0mo** [comment]
Hi again!

Do you have an example where you control the wings of your fly model by using torque control? 

Thanks in advance!

**Comment by vaxenburg** [comment]
Sure, in fact we used nothing but torque control for the wings

**Comment by Er1ckR0mo** [comment]
could you please refer me to it?

**Comment by vaxenburg** [comment]
Do you mean the flight task? It's here:
https://github.com/TuragaLab/flybody/blob/main/flybody/fly_envs.py#L29
https://github.com/TuragaLab/flybody/blob/main/flybody/tasks/flight_imitation.py#L16

**Comment by Er1ckR0mo** [comment]
Thanks! Going to check these.
I am interested in knowing how the torques are inputted to the actuators in mujoco and how these torque values are selected/updated during the task.
