### ISSUE TITLE
walk_imitation data format

### ISSUE THREAD

**Issue by KevinBian107** [TuragaLab/flybody#8]
Hi team,

I am trying to do imitation with rodent data and I was thinking to convert our STAC data to a similar format with you guys' data. However, I am not too sure about what is joint_quat, root2site, root_qpos, and root_qvel. Would it be possible to also give some guidance on your data preprocessing steps? Thanks for all the help.

This is what I got from reading the fly walking h5 file:
Dataset: trajectories/00000/joint_quat
    shape: (90, 102, 4)
    dtype: float32
Dataset: trajectories/00000/root2site
    shape: (90, 6, 3)
    dtype: float32
Dataset: trajectories/00000/root_qpos
    shape: (90, 7)
    dtype: float32
Dataset: trajectories/00000/root_qvel
    shape: (90, 6)
    dtype: float32
    
I saw this processing with the walker data: (https://github.com/TuragaLab/flybody/blob/2268560c5ea06cb6ed062ca5a8491f0442d67f09/flybody/tasks/rewards.py#L37 ) is this a similar process done on the reference trajectory?

**Comment by vaxenburg** [comment]
Hi Kevin, yes, the final step in the reference data preparation was exactly the same as in the `get_walker_features` function you referenced. And the starting point for that was the inverse kinematics fitting described in the last two paragraphs of the "Reference walking data preparation" section of our [preprint](https://www.biorxiv.org/content/10.1101/2024.03.11.584515v1). Let me know if it's not very clear?

**Comment by KevinBian107** [comment]
I see, thanks for the help again, I see that we need to get the `xaxis` for pointing directions of the joints to combine with qpos. I see how we can extract such value from the xml model for the Mujoco agent, but I am not sure how we would do so for trajectory data (250 frame per clips).

Thanks for all the help!

**Comment by vaxenburg** [comment]
Probably one way of getting the joint axis direction is first to do inverse kinematics fitting of the body model to the reference data, and then get the joint axis direction from that fitted body model -- that's how we do it anyway. But there could be other ways I guess?
